# Dependencies
highlighter:      rouge
gems: [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        pretty

# Setup
title:            Tyler McCraw
tagline:          'An Android blog'
description:      'A blog on Android development and other trains of thoughts.<br>Made by <a href="https://twitter.com/w3bshark" target="_blank">@w3bshark</a>.'
url:              http://w3bshark.com
baseurl:          /

author:
  name:           'Tyler McCraw'
  url:            https://twitter.com/w3bshark

paginate:         5

# Custom vars
github:			  https://github.com/tylermccraw
